# Generated by Django 3.0.4 on 2020-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ifsc', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=10)),
                ('contactNumber', models.IntegerField(max_length=10)),
                ('profilePicture', models.FileField(default='images/male_profile.png', upload_to='')),
            ],
        ),
    ]
