# Generated by Django 3.0.4 on 2020-03-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChequeClearingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='accountNumber',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
