# Generated by Django 3.0.4 on 2020-03-18 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChequeClearingSystem', '0002_auto_20200318_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='accountNumber',
            field=models.IntegerField(default=1000000, unique=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
