# Generated by Django 3.0.4 on 2020-03-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0004_accountholder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='signature',
            field=models.FileField(default='images/female.jpg', upload_to=''),
        ),
    ]
