# Generated by Django 3.0.4 on 2020-03-25 05:33

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChequeClearingSystem', '0005_accountholder_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='bearerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(default=1000000, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ifsc', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=10)),
                ('contactNumber', models.IntegerField()),
                ('profilePicture', models.FileField(default='images/male_profile.png', upload_to='')),
                ('signature', models.FileField(default='images/female.jpg', upload_to='')),
                ('dateOfBirth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('balance', models.IntegerField(default=10000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='bearerBankCheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque', models.FileField(upload_to='')),
                ('accountNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('timeDeposited', models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 33, 55, 37301))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payeeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.IntegerField(default=1000000, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ifsc', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=10)),
                ('contactNumber', models.IntegerField()),
                ('profilePicture', models.FileField(default='images/male_profile.png', upload_to='')),
                ('signature', models.FileField(default='images/female.jpg', upload_to='')),
                ('dateOfBirth', models.DateField(default=datetime.date(1970, 1, 1))),
                ('balance', models.IntegerField(default=10000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='payeeBankCheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque', models.FileField(upload_to='')),
                ('accountNumber', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('timeDeposited', models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 33, 55, 36920))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='AccountHolder',
        ),
    ]
