# Generated by Django 3.0.4 on 2020-03-25 05:35

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0006_auto_20200325_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 35, 26, 774880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 35, 26, 774483, tzinfo=utc)),
        ),
    ]
