# Generated by Django 3.0.4 on 2020-03-25 05:36

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0007_auto_20200325_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 36, 28, 641695, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 5, 36, 28, 641311, tzinfo=utc)),
        ),
    ]
