# Generated by Django 3.0.4 on 2020-04-01 05:07

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0016_auto_20200326_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bearerbank',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='payeebank',
            name='ifsc',
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='accountNumber',
            field=models.IntegerField(default=1000000, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='balance',
            field=models.IntegerField(default=10000, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='contactNumber',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='fatherName',
            field=models.CharField(max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='motherName',
            field=models.CharField(max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='pan',
            field=models.CharField(max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='profilePicture',
            field=models.FileField(default='images/male_profile.png', upload_to='', verbose_name='Photograph'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Account Registered'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='signature',
            field=models.FileField(default='images/female.jpg', upload_to='', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='accountNumber',
            field=models.IntegerField(verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='cheque',
            field=models.FileField(upload_to='', verbose_name='Cheque Image'),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.payeeBank', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Deposited'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='accountNumber',
            field=models.IntegerField(default=1000000, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='balance',
            field=models.IntegerField(default=10000, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='contactNumber',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='fatherName',
            field=models.CharField(max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='motherName',
            field=models.CharField(max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='pan',
            field=models.CharField(max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='profilePicture',
            field=models.FileField(default='images/male_profile.png', upload_to='', verbose_name='Photograph'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Account Registered'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='signature',
            field=models.FileField(default='images/female.jpg', upload_to='', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='accountNumber',
            field=models.IntegerField(verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='cheque',
            field=models.FileField(upload_to='', verbose_name='Cheque Image'),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.payeeBank', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='payeebankcheque',
            name='timeDeposited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Deposited'),
        ),
    ]
