# Generated by Django 3.0.4 on 2020-04-01 06:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0017_auto_20200401_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearerbank',
            name='lastTransaction',
            field=models.DateField(default=datetime.date(1970, 1, 1), null=True, verbose_name='Last Transaction'),
        ),
        migrations.AddField(
            model_name='payeebank',
            name='lastTransaction',
            field=models.DateField(default=datetime.date(1970, 1, 1), null=True, verbose_name='Last Transaction'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
