# Generated by Django 3.0.4 on 2020-04-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0019_auto_20200401_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='lastTransaction',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last Transaction'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='lastTransaction',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Last Transaction'),
        ),
    ]
