# Generated by Django 3.0.4 on 2020-04-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0021_auto_20200401_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bearerbankcheque',
            name='registered',
        ),
        migrations.AddField(
            model_name='bearerbank',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Account Registered'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
    ]
