# Generated by Django 3.0.4 on 2020-04-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0023_auto_20200401_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearerbankcheque',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.bearerBank', verbose_name='User'),
        ),
    ]
