# Generated by Django 3.0.4 on 2020-04-01 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0024_auto_20200401_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bearerbankcheque',
            name='client',
        ),
        migrations.RemoveField(
            model_name='payeebankcheque',
            name='client',
        ),
        migrations.AddField(
            model_name='bearerbankcheque',
            name='bearer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.bearerBank', verbose_name='Bearer'),
        ),
        migrations.AddField(
            model_name='bearerbankcheque',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.payeeBank', verbose_name='Payee'),
        ),
        migrations.AddField(
            model_name='payeebankcheque',
            name='bearer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.bearerBank', verbose_name='Bearer'),
        ),
        migrations.AddField(
            model_name='payeebankcheque',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='ChequeClearingSystem.payeeBank', verbose_name='Payee'),
        ),
    ]
