# Generated by Django 3.0.4 on 2020-04-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ChequeClearingSystem', '0025_auto_20200401_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bearerbankcheque',
            old_name='accountNumber',
            new_name='chequeNumber',
        ),
        migrations.RenameField(
            model_name='payeebankcheque',
            old_name='accountNumber',
            new_name='chequeNumber',
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='bearerbank',
            name='lastTransaction',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Transaction'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='payeebank',
            name='lastTransaction',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Transaction'),
        ),
    ]
